/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Cajones;
import Model.Clientes;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import java.util.Calendar;

/**
 *
 * @author JODA
 */
public class aparcar extends javax.swing.JFrame {
DefaultComboBoxModel modelo =new DefaultComboBoxModel (); //creamos el modelo del combobox
int L;   //variables y objeto calendar.
boolean f=true;
private Reloj.Hora hora;
Calendar re=Calendar.getInstance();

//Cajones cajon = new Cajones();
    /**
     * Creates new form aparcar
     */
    public aparcar() {  //establecemos propiedades a la ventana, quitamos decoración...
        this.setUndecorated(true);
        this.setLocation(400, 100);
        initComponents();
        L=1;
        this.combocajon.setModel(modelo);   //aplicamos el modelo al combobox
        hora= new Reloj.Hora();             //pintamos un nuevo reloj que con ayuda del jclock creamos.
                hora.setForeground(Color.red);
        hora.setBounds(120, 1, 150, 30);/*(Ubicacion en eje x, Ubicacion en eje y, Ancho, Alto)*/
        hora.setFont(new Font("Trebuchet MS",java.awt.Font.BOLD, 20));/*Cambiamos la fuente, estilo y tamaño*/
        this.panel.add(hora);
       System.out.println(re.get(Calendar.HOUR)+": "+re.get(Calendar.MINUTE)+": "+re.get(Calendar.SECOND));
        System.out.println(L); 
       while (L<12){           //llenamos el combobox con los cajones disponibles.
            Cajones cajon= new Cajones(L);
          if(cajon.getEstado()==0){
              System.out.println(cajon.getEstado()+"estrados");
          Object caj= cajon.getNumero();
              System.out.println("estoes"+caj+"" );
          modelo.addElement(caj);
          L++;
        }
          else{
              L++;
          }         
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmpPlaca = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cmpCliente = new javax.swing.JTextField();
        cmpCorreo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmpMarca_modelo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        combocajon = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnlisto = new javax.swing.JButton();
        panel = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jTextField2.setText("jTextField2");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(460, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 204, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Ganacias ");
        jLabel8.setToolTipText("Ganancias \nOptimas");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, 50));

        jLabel5.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 204, 255));
        jLabel5.setText("45%");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 110, 50));

        cmpPlaca.setBorder(null);
        cmpPlaca.setOpaque(false);
        cmpPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmpPlacaActionPerformed(evt);
            }
        });
        getContentPane().add(cmpPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 217, 313, 25));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/flat/placalabe.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        cmpCliente.setBorder(null);
        cmpCliente.setOpaque(false);
        getContentPane().add(cmpCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 260, 310, 30));

        cmpCorreo.setBorder(null);
        cmpCorreo.setOpaque(false);
        getContentPane().add(cmpCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 305, 310, 26));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/flat/labepropietario.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 450, -1));

        cmpMarca_modelo.setBorder(null);
        cmpMarca_modelo.setOpaque(false);
        getContentPane().add(cmpMarca_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 350, 315, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/flat/labemod.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 450, 50));

        combocajon.setOpaque(false);
        combocajon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combocajonActionPerformed(evt);
            }
        });
        getContentPane().add(combocajon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 310, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/flat/labelug.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 450, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/flat/babumenu.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/flat/labecel.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 450, -1));

        btnlisto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/flat/bRegis.png"))); // NOI18N
        btnlisto.setBorder(null);
        btnlisto.setFocusable(false);
        btnlisto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistoActionPerformed(evt);
            }
        });
        getContentPane().add(btnlisto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        panel.setForeground(new java.awt.Color(255, 255, 255));
        panel.setFocusable(false);
        panel.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        panel.setOpaque(false);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 240, 30));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/flat/Exit.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 30, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/flat/backRegis.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 470));

        jButton4.setText("jButton4");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        jButton5.setText("jButton5");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private double tiempo(){//retornamos el tiempo actual.
        int hora=re.get(Calendar.HOUR);
        double minuto=re.get(Calendar.MINUTE)/100.000;
        double tiempo= hora+minuto;
        System.out.println("Hora: "+hora+"     minuto: "+minuto+"      tiempo: "+tiempo);
        return tiempo;
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new menu().setVisible(true);
        System.out.println(L);
            this.dispose();      // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnlistoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistoActionPerformed
            Clientes cliente= new Clientes(this.cmpPlaca.getText(),this.cmpCliente.getText(),this.cmpCorreo.getText(), this.cmpMarca_modelo.getText(),Integer.parseInt(this.combocajon.getSelectedItem().toString()),tiempo());  
            Cajones cajon= new Cajones(Integer.parseInt(this.combocajon.getSelectedItem().toString()));
            cliente.Guardar();
            cajon.actualizar();  //creamos cliente y actualizamos cajones
    }//GEN-LAST:event_btnlistoActionPerformed

    private void combocajonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combocajonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combocajonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cmpPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmpPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmpPlacaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aparcar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aparcar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aparcar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aparcar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aparcar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlisto;
    private javax.swing.JTextField cmpCliente;
    private javax.swing.JTextField cmpCorreo;
    private javax.swing.JTextField cmpMarca_modelo;
    private javax.swing.JTextField cmpPlaca;
    private javax.swing.JComboBox combocajon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
