/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Cajones;
import Model.Datos;
import Model.Clientes;
import java.awt.Color;
import java.awt.Font;
import javax.swing.DefaultComboBoxModel;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author JODA
 */
public class aparcar extends javax.swing.JFrame {

    DefaultComboBoxModel modelo = new DefaultComboBoxModel(); //creamos el modelo del combobox
    int L;   //variables y objeto calendar.
    boolean f = true;
    private Reloj.Hora hora;
    Calendar re = Calendar.getInstance();
         int claseAut=0;

//Cajones cajon = new Cajones();
    /**
     * Creates new form aparcar
     */
    public aparcar() {  //establecemos propiedades a la ventana, quitamos decoración...
        this.setUndecorated(true);
        this.setLocation(400, 50);
        initComponents();
        L = 0;
        this.combocajon.setModel(modelo);   //aplicamos el modelo al combobox
        hora = new Reloj.Hora();             //pintamos un nuevo reloj que con ayuda del jclock creamos.
        hora.setForeground(Color.red);
        hora.setBounds(120, 10, 155, 30);/*(Ubicacion en eje x, Ubicacion en eje y, Ancho, Alto)*/
        hora.setFont(new Font("Trebuchet MS", java.awt.Font.BOLD, 20));/*Cambiamos la fuente, estilo y tamaño*/
        this.panel.add(hora);
        System.out.println(re.get(Calendar.HOUR) + ": " + re.get(Calendar.MINUTE) + ": " + re.get(Calendar.SECOND));
        System.out.println(L);
        while (L < 12) {           //llenamos el combobox con los cajones disponibles.
            Cajones cajon = new Cajones(L);
            //System.out.println(cajon+"Cajones");
            if (cajon.ConsultaCajon(L) != L && cajon.getEstado() == 0) {
                // Object caj= cajon.getNumero();
                Object caj = L;
                modelo.addElement(caj);
                L++;
            } else {
                L++;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        claseAuto = new javax.swing.JSlider();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmpLetters = new javax.swing.JTextField();
        cpmNumbers = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cmpCliente = new javax.swing.JTextField();
        cmpCorreo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmpMarca_modelo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        combocajon = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnlisto = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cmp_observacion = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cmpPlaca = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(456, 640));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        claseAuto.setForeground(new java.awt.Color(28, 189, 235));
        claseAuto.setMajorTickSpacing(5);
        claseAuto.setMaximum(5);
        claseAuto.setMinimum(1);
        claseAuto.setMinorTickSpacing(1);
        claseAuto.setPaintLabels(true);
        claseAuto.setValue(1);
        claseAuto.setOpaque(false);
        claseAuto.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                claseAutoStateChanged(evt);
            }
        });
        getContentPane().add(claseAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 370, 50));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/flat/babumenu.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 315, 10, 28));

        jLabel8.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 204, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Ganacias ");
        jLabel8.setToolTipText("Ganancias \nOptimas");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, 50));

        jLabel5.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 204, 255));
        jLabel5.setText("45%");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 110, 50));

        cmpLetters.setFont(new java.awt.Font("DejaVu Sans", 3, 30));
        cmpLetters.setBorder(null);
        cmpLetters.setOpaque(false);
        cmpLetters.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmpLettersMouseClicked(evt);
            }
        });
        cmpLetters.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cmpLettersMouseMoved(evt);
            }
        });
        cmpLetters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmpLettersActionPerformed(evt);
            }
        });
        cmpLetters.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmpLettersPropertyChange(evt);
            }
        });
        getContentPane().add(cmpLetters, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 315, 73, 27));

        cpmNumbers.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        cpmNumbers.setBorder(null);
        cpmNumbers.setOpaque(false);
        getContentPane().add(cpmNumbers, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 315, 44, 26));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/flat/placalabe.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 440, 60));

        cmpCliente.setBorder(null);
        cmpCliente.setOpaque(false);
        getContentPane().add(cmpCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 360, 310, 30));

        cmpCorreo.setBorder(null);
        cmpCorreo.setOpaque(false);
        getContentPane().add(cmpCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 415, 310, 26));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/flat/labepropietario.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 450, -1));

        cmpMarca_modelo.setBorder(null);
        cmpMarca_modelo.setOpaque(false);
        getContentPane().add(cmpMarca_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 459, 315, 28));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/flat/labemod.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 450, 50));

        combocajon.setOpaque(false);
        combocajon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combocajonActionPerformed(evt);
            }
        });
        getContentPane().add(combocajon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 311, 29));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/flat/labelug.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 450, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/flat/babumenu.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 40, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/flat/labecel.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 450, -1));

        btnlisto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/flat/bRegis.png"))); // NOI18N
        btnlisto.setBorder(null);
        btnlisto.setFocusable(false);
        btnlisto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistoActionPerformed(evt);
            }
        });
        getContentPane().add(btnlisto, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 597, -1, 20));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/flat/Exit.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 30, 30));

        cmp_observacion.setColumns(20);
        cmp_observacion.setRows(5);
        cmp_observacion.setOpaque(false);
        getContentPane().add(cmp_observacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 549, 312, 43));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/flat/labeObser.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 450, 70));

        panel.setForeground(new java.awt.Color(255, 255, 255));
        panel.setFocusable(false);
        panel.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        panel.setOpaque(false);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 240, 50));

        jLabel6.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/flat/backRegis.png"))); // NOI18N
        jLabel6.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jLabel6ComponentAdded(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 460, 700));

        cmpPlaca.setBorder(null);
        cmpPlaca.setOpaque(false);
        cmpPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmpPlacaActionPerformed(evt);
            }
        });
        getContentPane().add(cmpPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 120, 25));

        jButton4.setText("jButton4");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        jButton5.setText("jButton5");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private double tiempo() {//retornamos el tiempo actual.
        int hora = re.get(Calendar.HOUR);
        double minuto = re.get(Calendar.MINUTE) / 100.000;
        double tiempo = hora + minuto;
        System.out.println("Hora: " + hora + "     minuto: " + minuto + "      tiempo: " + tiempo);
        return tiempo;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new menu().setVisible(true);
        System.out.println(L);
        this.dispose();      // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnlistoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistoActionPerformed
        StringBuilder letrasPla = new StringBuilder(cmpLetters.getText());
        StringBuilder numberPla = new StringBuilder(cpmNumbers.getText());
        StringBuilder Placa = new StringBuilder(cpmNumbers.getText());
        Datos revDatos = new Datos();
        Placa = revDatos.Placa(letrasPla, numberPla);
        if(Placa.length()<6){
                JOptionPane.showMessageDialog(rootPane, "No se puede continuar"+ claseAut);
        }else{
                    Clientes cliente= new Clientes(Placa.toString(),this.cmpCliente.getText(),this.cmpCorreo.getText(), this.cmpMarca_modelo.getText(),Integer.parseInt(this.combocajon.getSelectedItem().toString()),tiempo(),this.cmp_observacion.getText(),claseAut);  
                    Cajones cajon1= new Cajones(Integer.parseInt(this.combocajon.getSelectedItem().toString()),0,claseAut);
                    Cajones cajoncons= new Cajones(Integer.parseInt(this.combocajon.getSelectedItem().toString()));
                    if(this.cmpLetters.getText().length()==0 || this.cmpCliente.getText().length()==0 || this.cmpMarca_modelo.getText().length()==0 || this.cmp_observacion.getText().length()==0 || this.cmpCorreo.getText().length()==0  ){
                    JOptionPane.showMessageDialog(null,"Falta informacion por llenar!", "Llenar informacion Faltante",1); 
                    }else{
                    if(cajoncons.ConsultaCajon(Integer.parseInt(this.combocajon.getSelectedItem().toString()))==0){
                    cajon1.Guardar();
                    cliente.Guardar();
                    }
                    }
        }
    

        /*Clientes cliente= new Clientes(this.cmpPlaca.getText(),this.cmpCliente.getText(),this.cmpCorreo.getText(), this.cmpMarca_modelo.getText(),Integer.parseInt(this.combocajon.getSelectedItem().toString()),tiempo(),this.cmp_observacion.getText());  
            Cajones cajon1= new Cajones(Integer.parseInt(this.combocajon.getSelectedItem().toString()),0);
            Cajones cajoncons= new Cajones(Integer.parseInt(this.combocajon.getSelectedItem().toString()));
           if(this.cmpPlaca.getText().length()==0 && this.cmpCliente.getText().length()==0 && this.cmpMarca_modelo.getText().length()==0 && this.cmp_observacion.getText().length()==0  ){
                  JOptionPane.showMessageDialog(null,"Falta informacion por llenar!", "Llenar informacion Faltante",1); 
            }else{
                 if(cajoncons.ConsultaCajon(Integer.parseInt(this.combocajon.getSelectedItem().toString()))==0){
               cajon1.Guardar();
               cliente.Guardar();
                 }
           }
      
         */
        //creamos cliente y actualizamos cajones
    }//GEN-LAST:event_btnlistoActionPerformed

    private void combocajonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combocajonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combocajonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cmpPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmpPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmpPlacaActionPerformed

    private void jLabel6ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jLabel6ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6ComponentAdded

    private void claseAutoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_claseAutoStateChanged
        // TODO add your handling code here:
                        Datos datoscli = new Datos();
     claseAut = (int)claseAuto.getValue();
       switch(claseAut){ case 0:
                cmpLetters.setText("");
                cpmNumbers.setText("");
                datoscli.isCaden(cmpLetters, 2);
                datoscli.isProbar(cpmNumbers, 2);
                break;
           
            case 1:
                cmpLetters.setText("");
                cpmNumbers.setText("");
                datoscli.isCaden(cmpLetters, 2);
                datoscli.isProbar(cpmNumbers, 2);
                break;
            case 2:
                cmpLetters.setText("");
                cpmNumbers.setText("");
                datoscli.isCaden(cmpLetters, 2);
                datoscli.isProbar(cpmNumbers, 2);
                break;
                     case 3:
                cmpLetters.setText("");
                cpmNumbers.setText("");
                datoscli.isCaden(cmpLetters, 2);
                datoscli.isProbar(cpmNumbers, 2);
                break;
                                     case 4:
                cmpLetters.setText("");
                cpmNumbers.setText("");
                datoscli.isCaden(cmpLetters, 2);
                datoscli.isProbar(cpmNumbers, 2);
                break;
                                     case 5:
                cmpLetters.setText("");
                cpmNumbers.setText("");
                datoscli.isCaden(cmpLetters, 2);
                datoscli.isProbar(cpmNumbers, 2);
                break;
        }

    }//GEN-LAST:event_claseAutoStateChanged

    private void cmpLettersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmpLettersActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cmpLettersActionPerformed

    private void cmpLettersPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmpLettersPropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_cmpLettersPropertyChange

    private void cmpLettersMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmpLettersMouseMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_cmpLettersMouseMoved

    private void cmpLettersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmpLettersMouseClicked
        // TODO add your handling code here
      
    }//GEN-LAST:event_cmpLettersMouseClicked

    /**
     * @param args the command line arguments
     */
        public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aparcar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aparcar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aparcar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aparcar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aparcar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlisto;
    private javax.swing.JSlider claseAuto;
    private javax.swing.JTextField cmpCliente;
    private javax.swing.JTextField cmpCorreo;
    private javax.swing.JTextField cmpLetters;
    private javax.swing.JTextField cmpMarca_modelo;
    private javax.swing.JTextField cmpPlaca;
    private javax.swing.JTextArea cmp_observacion;
    private javax.swing.JComboBox combocajon;
    private javax.swing.JTextField cpmNumbers;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
