package View;
import Model.CambioValor;
import Model.DB;
import Model.usuarios;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import javax.swing.JOptionPane;
/**
 *
 * @author JODA
 */
public class CambioValores extends javax.swing.JFrame {
int clasecat=1;
    Calendar re = Calendar.getInstance();
             CambioValor a1 = new CambioValor();
    public CambioValores() {
        initComponents();
        cmpPagar.setText(""+a1.ultimoValor_id(1));
        cmpVehiculo.setText(""+1);
        
        
    }
public int llenar_id(){  //añadimos una nueva ID a los parámetros 
     CambioValor start = new CambioValor();
          int newid=start.ultimoCajon(clasecat);
      return newid;
}
public int Saber_id(){  //añadimos una nueva ID a los parámetros 
     CambioValor start = new CambioValor();
       int newid = start.ultimo_id(clasecat);
      return newid;
}
public int Sabervar_id(){  //añadimos una nueva ID a los parámetros 
     CambioValor start = new CambioValor();
       int newid=start.ultiValor_id(clasecat);
      return newid;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private String tiempo() {
        String tiempo =""+ Integer.toString(re.get(Calendar.YEAR))+"/"+Integer.toString(re.get(Calendar.MONTH)+ 1)+"/"+Integer.toString(re.get(Calendar.DATE))+" "+Integer.toString(re.get(Calendar.HOUR_OF_DAY))+":"+Integer.toString(re.get((Calendar.MINUTE)))+":"+Integer.toString(re.get((Calendar.SECOND)));
        System.out.println("Tiempo"+tiempo);
        return tiempo;
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Escogerca = new javax.swing.JSlider();
        cmpVehiculo = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        cmpCajon = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cmpPagar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(241, 252, 255));
        jLabel1.setText("Ultimo Cambio:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, 290, 30));
        CambioValor fecha  = new CambioValor(1);
        this.jLabel1.setText("Ultimo Cambio:"+fecha.getFecha());

        Escogerca.setForeground(new java.awt.Color(239, 240, 240));
        Escogerca.setMajorTickSpacing(1);
        Escogerca.setMaximum(5);
        Escogerca.setMinimum(1);
        Escogerca.setMinorTickSpacing(1);
        Escogerca.setPaintLabels(true);
        Escogerca.setPaintTicks(true);
        Escogerca.setValue(1);
        Escogerca.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                EscogercaStateChanged(evt);
            }
        });
        getContentPane().add(Escogerca, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 440, -1));

        cmpVehiculo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cmpVehiculo.setForeground(new java.awt.Color(204, 204, 204));
        cmpVehiculo.setBorder(null);
        cmpVehiculo.setOpaque(false);
        getContentPane().add(cmpVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 440, 30));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/flat/createMen.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 40, 30));
        jButton5.getAccessibleContext().setAccessibleDescription("");

        cmpCajon.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cmpCajon.setForeground(new java.awt.Color(204, 204, 204));
        cmpCajon.setBorder(null);
        cmpCajon.setText(""+llenar_id());
        cmpCajon.setOpaque(false);
        cmpCajon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cmpCajonKeyTyped(evt);
            }
        });
        getContentPane().add(cmpCajon, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 440, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cajones");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/flat/createCan.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 220, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Valor a Pagar Diario");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        cmpPagar.setOpaque(false);
        cmpPagar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cmpPagarKeyTyped(evt);
            }
        });
        getContentPane().add(cmpPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 440, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tipo de Vehiculo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/flat/createGuar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 220, 30));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/flat/updaPer.png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, -1, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/flat/Createpro.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        
        new Update_user().setVisible(true);
       this.dispose();        
        /* JOptionPane.showMessageDialog(null,"-Si va a añadir un nuevo usuario rellene todos los campos\n"
                + "-Si va a modificar un registro Tiene que llenar el campo de Nombre por el que desee modificar\n"
                + "asi como los campos a modificar.\n-Si va a eliminar un registro Solo rellene el Nombre del registro a eliminar.\n\n"
                + " Cualquier duda consulte al administrador.","información",1);   
        */
// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed
                    //creamos un nuevo usuario a partir de los datos que estén en los campos de texto.
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(this.cmpCajon.getText().equals("")||this.cmpPagar.getText().equals("")||this.cmpVehiculo.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Campos incompletos","error",1);
        }else{
           int ultimo = Sabervar_id();
   CambioValor cambi1 = new CambioValor(llenar_id(),Integer.parseInt(this.cmpCajon.getText()),Integer.parseInt(this.cmpPagar.getText()),Integer.parseInt(this.cmpVehiculo.getText()),tiempo());
        cambi1.setIdUsuario(Sabervar_id());
        cambi1.setCajon(Integer.parseInt(this.cmpCajon.getText()));
        cambi1.setValorpa(Integer.parseInt(this.cmpPagar.getText()));
        cambi1.setFecha(tiempo());
        cambi1.actualizar(ultimo);
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       new Login().setVisible(true);
       this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
  new menu().setVisible(true);
       this.dispose();        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void EscogercaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_EscogercaStateChanged
        // TODO add your handling code here:
            clasecat = (int)Escogerca.getValue();
       switch(clasecat){ 
            case 1:
                 CambioValor fecha  = new CambioValor(1);
            cmpCajon.setText(""+llenar_id());
            cmpPagar.setText(""+a1.ultimoValor_id(1));
            jLabel4.setText("Tipo de Vehiculo"+" Moto");
            cmpVehiculo.setText(""+1);
            cmpVehiculo.enable(false);
            this.jLabel1.setText("Ultimo Cambio:"+fecha.getFecha());
            
                break;
            case 2:
                CambioValor fecha2  = new CambioValor(2);
                 cmpCajon.setText(""+llenar_id());
            cmpPagar.setText(""+a1.ultimoValor_id(2));
                        jLabel4.setText("Tipo de Vehiculo"+" Carro");
            cmpVehiculo.setText(""+2);
            cmpVehiculo.enable(false);
                        this.jLabel1.setText("Ultimo Cambio:"+fecha2.getFecha());
            
                break;
                     case 3:
                         cmpCajon.setText(""+llenar_id());
            cmpPagar.setText(""+a1.ultimoValor_id(3));
                        jLabel4.setText("Tipo de Vehiculo"+" Camion");
            cmpVehiculo.setText(""+3);
            cmpVehiculo.enable(false);
               CambioValor fecha3  = new CambioValor(3);
                this.jLabel1.setText("Ultimo Cambio:"+fecha3.getFecha());
                break;
                                     case 4:
                                        cmpCajon.setText(""+llenar_id());
                                        jLabel4.setText("Tipo de Vehiculo"+" Mula");
                                        cmpPagar.setText(""+a1.ultimoValor_id(4));
                                        cmpVehiculo.setText(""+4);
                                        cmpVehiculo.enable(false);
                                        CambioValor fecha4  = new CambioValor(4);
                                        this.jLabel1.setText("Ultimo Cambio:"+fecha4.getFecha());

               
                break;
                                     case 5:
                                         cmpCajon.setText(""+llenar_id());
                                         jLabel4.setText("Tipo de Vehiculo"+" Maquina");
                                         cmpPagar.setText(""+a1.ultimoValor_id(5));
                                         cmpVehiculo.setText(""+5);
                                         cmpVehiculo.enable(false);
                                         CambioValor fecha5  = new CambioValor(5);
                                         this.jLabel1.setText("Ultimo Cambio:"+fecha5.getFecha());

                break;
        }
        

    }//GEN-LAST:event_EscogercaStateChanged

    private void cmpCajonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmpCajonKeyTyped
        // TODO add your handling code here:
        char c= evt.getKeyChar();
                                    int a1 = cmpCajon.getText().length();
                                    if(!Character.isDigit(c)){
                                        evt.consume();
                                    }
    }//GEN-LAST:event_cmpCajonKeyTyped

    private void cmpPagarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmpPagarKeyTyped
        // TODO add your handling code here:
                char c= evt.getKeyChar();
                                    int a1 = cmpPagar.getText().length();
                                    if(!Character.isDigit(c)){
                                        evt.consume();
                                    }
    }//GEN-LAST:event_cmpPagarKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambioValores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambioValores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambioValores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambioValores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CambioValores().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider Escogerca;
    private javax.swing.JTextField cmpCajon;
    private javax.swing.JTextField cmpPagar;
    private javax.swing.JTextField cmpVehiculo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
