/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.CambioValor;
import Model.Clientes;
import Model.DB;
import Model.Horas;
import static View.retiro.Redondear;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import javax.swing.JLabel;

/**
 *
 * @author JODA
 */
public class data extends javax.swing.JFrame {
    DB base= new DB(); //instanciamos la clase de conexión  
    public static Connection conexion;  //obtenemos conexión con ayuda de la clase.
    
    /**
     * Creates new form dataa
     */
    public data() {
        this.setUndecorated(true); //quitamos la decoración de la ventana
        //actualizar_datos(1);
        //this.setOpacity(0.75f); //decimos que sea 75% opaco / 25% transparente.
        initComponents();


        //myInitComponents();
           
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ET_Placa = new javax.swing.JLabel();
        ET_Propietario = new javax.swing.JLabel();
        ET_Vehiculo = new javax.swing.JLabel();
        ET_Valor = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Datos Generales");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Placa:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Propietario");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Vehículo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/animacion.gif"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, 76));

        ET_Placa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ET_Placa.setForeground(new java.awt.Color(0, 255, 0));
        ET_Placa.setText("Placa");
        ET_Placa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ET_PlacaMouseEntered(evt);
            }
        });
        getContentPane().add(ET_Placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 170, 20));

        ET_Propietario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ET_Propietario.setForeground(new java.awt.Color(102, 255, 0));
        ET_Propietario.setText("DUEÑO");
        getContentPane().add(ET_Propietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 130, -1));

        ET_Vehiculo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ET_Vehiculo.setForeground(new java.awt.Color(102, 255, 0));
        ET_Vehiculo.setText("CARRO");
        getContentPane().add(ET_Vehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 150, 20));

        ET_Valor.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        ET_Valor.setForeground(new java.awt.Color(240, 244, 245));
        ET_Valor.setText("Valor:");
        getContentPane().add(ET_Valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        jLabel8.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 25, 0));
        jLabel8.setText("Valor");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 150, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/fondo_data.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 240, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
                  data a = new data();
          a.actualizar_datos(1);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void ET_PlacaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ET_PlacaMouseEntered
        //ET_Placa.setText("Hola");
        //ET_Propietario.setText("hola");
        // TODO add your handling code here:
    }//GEN-LAST:event_ET_PlacaMouseEntered

    public void actualizar_datos(int Cajon_Numero){  //actualiamos los datos que vamos a mostrar dependiendo el cajón
        conexion = base.GetConnection();
        PreparedStatement select;
        try {
            select = conexion.prepareStatement("select * from cliente where Cajon_Numero= '"+Cajon_Numero+"'");
            boolean consulta = select.execute();
            if(consulta){
                ResultSet resultado =  select.executeQuery();
                if(resultado.next()){
                    this.ET_Placa.setText( resultado.getString(1));
                    this.ET_Propietario.setText(resultado.getString(2));
                    this.ET_Vehiculo.setText(resultado.getString(4));
                   
                }
                
                ///*
                else{
                    resultado.close();
                }
                //*/
                resultado.close();
            }
            conexion.close();
        } catch (SQLException ex) {
            System.err.println("Ocurrió un error: "+ex.getMessage().toString());
        }
    }
    Calendar re=Calendar.getInstance();
        private String fecha(){  
        String fecha =""+ Integer.toString(re.get(Calendar.YEAR))+"/"+Integer.toString(re.get(Calendar.MONTH) + 1)+"/"+Integer.toString(re.get(Calendar.DATE))+" "+Integer.toString(re.get(Calendar.HOUR_OF_DAY))+":"+Integer.toString(re.get((Calendar.MINUTE)))+":"+Integer.toString(re.get((Calendar.SECOND)));
            return fecha;
        
    }
    public void actualizar_valor(int Cajon_Numero){  //actualiamos los datos que vamos a mostrar dependiendo el cajón
        try{
          Clientes client= new Clientes(Cajon_Numero);        
          String llegada= client.getLlegada();
            System.out.println("Fecha llegada::"+llegada);
          String Salida = fecha();
          System.out.println("Fecha Salida::"+Salida);
            Horas cambio = new Horas();
            long diferencia = cambio.retornaDiferencia(llegada,Salida);
            long horas = cambio.retornaHoras(llegada, Salida);
            long minutos = cambio.retornaMinutos(llegada, Salida);
            long segundos = cambio.retornaSegundos(llegada, Salida);
            CambioValor vtar  = new CambioValor(client.getTipove());
            int vpo = vtar.getValorpa();
            double valor = (double) vpo/1440;
            double resultado = diferencia*valor;
            resultado = Redondear(resultado, 1);
            this.jLabel8.setText(""+resultado); //y el pago. diciéndole que solo ocupamos 2 cifras después del punto decimal.
       }
       catch(Exception ex){
           System.out.println("error"+ ex.getMessage());
       }
    }
      public void update(){  //actualiamos los datos que vamos a mostrar dependiendo el cajón
                                      this.ET_Placa.setText( "Placa    ");
                    this.ET_Propietario.setText("Propietario    ");
                  this.ET_Vehiculo.setText("Vehiculo     ");
                  this.ET_Valor.setText("VALOR");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         *
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               data data=new data();
                        data.setVisible(true);
                        
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel ET_Placa;
    public javax.swing.JLabel ET_Propietario;
    private javax.swing.JLabel ET_Valor;
    public javax.swing.JLabel ET_Vehiculo;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
