/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.player;
import Model.usuarios;
import java.io.File;
import javax.swing.JOptionPane;
/**
 *
 * @author JODA
 */
public class Login extends javax.swing.JFrame {
    private player reproductor=null;   //esta es la instancia a mi clase que reproduce audio
    /**
     * Creates new form Login
     */
    public Login() {
        this.setLocation(400, 100);  //establezco las coordenadas de mi form
        this.setUndecorated(true);  // le quito la barra de título y los botones de arriba
        initComponents();
        reproducir_saludo();       //pues eso reproduce el saludo
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cmpusuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmpContraseña = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setEnabled(false);
        jButton2.setOpaque(false);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, 60, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/flat/In.png"))); // NOI18N
        jButton1.setToolTipText("");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 250, 50));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/flat/Opcion.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 550, 140, 70));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/flat/Exit.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 40, 40));

        cmpusuario.setBackground(new java.awt.Color(204, 204, 204));
        cmpusuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmpusuarioFocusGained(evt);
            }
        });
        getContentPane().add(cmpusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 250, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/flat/usr.png"))); // NOI18N
        jLabel2.setText("Usuario: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 310, 50));

        cmpContraseña.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(cmpContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 230, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/flat/Pass.png"))); // NOI18N
        jLabel3.setText("Contraseña:");
        jLabel3.setToolTipText("");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 300, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/flat/Login.png"))); // NOI18N
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents
            private void reproducir_1(){
        File rutarelativa= new File("");   //ocupo la ruta relativa ya que cambia cuando comparto la aplicación
       String ruutarel= rutarelativa.getAbsolutePath(); //transformo la ruta relativa a string para poder enviarla como parámetro
       System.out.println("    Ruta relativa:  "+ruutarel);
        reproductor=new player();      //instancio la variable a la clase
        reproductor.rep(ruutarel+"\\sonidos\\whoareyou.mp3");  //envío los parametros para que pueda sonar
        reproductor.start();   //inicio el hilo del proceso (no hilos de tejer!!)
    }
            //de aqui en adelante son metodos para reproducir determinados sonidos
            //no pude meter todos los sonidos en un método ya que cada instancia acepta solo una reproduccion
            private void reproducir_error(){
        File rutarelativa= new File("");
       String ruutarel= rutarelativa.getAbsolutePath();
       System.out.println("    Ruta relativa:  "+ruutarel);
        reproductor=new player();
        reproductor.rep(ruutarel+"\\sonidos\\unknowerror.mp3");
        reproductor.start();
    }
            
            private void reproducir_saludo(){
        File rutarelativa= new File("");
       String ruutarel= rutarelativa.getAbsolutePath();
       System.out.println("    Ruta relativa:  "+ruutarel);
        reproductor=new player();
        reproductor.rep(ruutarel+"\\sonidos\\hello.mp3");
        reproductor.start();
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cmpusuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmpusuarioFocusGained
        reproducir_1();        // TODO add your handling code here:
    }//GEN-LAST:event_cmpusuarioFocusGained

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new alta_usuario().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            usuarios usu = new usuarios(this.cmpusuario.getText());
            String  passoriginal= usu.getCostraseña();
            String  pass= new String(cmpContraseña.getPassword());
            System.out.println("Contraseña original: "+passoriginal+"   contraseña escrita: "+pass);
            if(pass.equals("Joda10")){      //tipico ciclo de verificación de contraseña y usuario.
                //JOptionPane.showMessageDialog(null, "Exito", "sucess",2);
                new menu().setVisible(true);
                this.dispose();
                System.out.println("Contraseña original: "+passoriginal+"   contraseña escrita: "+pass);
            }
            else{
                reproducir_error();
                JOptionPane.showMessageDialog(null, "Datos Incorrectos", "Acceso denagado",2);
                //ojo que si pones la contraseña bien pero el user no tambien marca error ;)
        }
        }
        catch(Exception ex){
            ex.getMessage();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField cmpContraseña;
    private javax.swing.JTextField cmpusuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
