/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Cajones;
/**
 *
 * @author JODA
 */
public class mapa extends javax.swing.JFrame {
            data info= new data();
            int L;
             retiro ret= new retiro();
    /**
     * Creates new form mapa
     */
    public mapa() {
        this.setUndecorated(true);
        initComponents();
        info.setVisible(false);
        L=1; 
        actualizar_carros(); 
         this.boton_retirada1.setVisible(false);
         this.boton_retirada.setVisible(false);
         this.boton_retirada2.setVisible(false);
         this.boton_retirada3.setVisible(false);
         this.boton_retirada4.setVisible(false);
         this.boton_retirada5.setVisible(false);
         this.boton_retirada6.setVisible(false);
         this.boton_retirada7.setVisible(false);
         this.boton_retirada8.setVisible(false);
         this.boton_retirada9.setVisible(false);
         this.boton_retirada10.setVisible(false);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boton_retirada1 = new javax.swing.JButton();
        boton_retirada2 = new javax.swing.JButton();
        boton_retirada3 = new javax.swing.JButton();
        boton_retirada4 = new javax.swing.JButton();
        boton_retirada5 = new javax.swing.JButton();
        boton_retirada6 = new javax.swing.JButton();
        boton_retirada7 = new javax.swing.JButton();
        boton_retirada8 = new javax.swing.JButton();
        boton_retirada9 = new javax.swing.JButton();
        boton_retirada10 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        boton_retirada = new javax.swing.JButton();
        carro_1 = new javax.swing.JLabel();
        carro_2 = new javax.swing.JLabel();
        carro_3 = new javax.swing.JLabel();
        carro_4 = new javax.swing.JLabel();
        carro_6 = new javax.swing.JLabel();
        carro_5 = new javax.swing.JLabel();
        carro_7 = new javax.swing.JLabel();
        carro_8 = new javax.swing.JLabel();
        carro_9 = new javax.swing.JLabel();
        carro_10 = new javax.swing.JLabel();
        carro_11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_retirada1.setText("Retirar");
        boton_retirada1.setFocusPainted(false);
        boton_retirada1.setFocusable(false);
        boton_retirada1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_retirada1ActionPerformed(evt);
            }
        });
        getContentPane().add(boton_retirada1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 230, -1, 20));

        boton_retirada2.setText("Retirar");
        boton_retirada2.setFocusPainted(false);
        boton_retirada2.setFocusable(false);
        boton_retirada2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_retirada2ActionPerformed(evt);
            }
        });
        getContentPane().add(boton_retirada2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, -1, 20));

        boton_retirada3.setText("Retirar");
        boton_retirada3.setFocusPainted(false);
        boton_retirada3.setFocusable(false);
        boton_retirada3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_retirada3ActionPerformed(evt);
            }
        });
        getContentPane().add(boton_retirada3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, -1, 20));

        boton_retirada4.setText("Retirar");
        boton_retirada4.setFocusPainted(false);
        boton_retirada4.setFocusable(false);
        boton_retirada4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_retirada4ActionPerformed(evt);
            }
        });
        getContentPane().add(boton_retirada4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, -1, -1));

        boton_retirada5.setText("Retirar");
        boton_retirada5.setFocusPainted(false);
        boton_retirada5.setFocusable(false);
        boton_retirada5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_retirada5ActionPerformed(evt);
            }
        });
        getContentPane().add(boton_retirada5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, -1, -1));

        boton_retirada6.setText("Retirar");
        boton_retirada6.setFocusPainted(false);
        boton_retirada6.setFocusable(false);
        boton_retirada6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_retirada6ActionPerformed(evt);
            }
        });
        getContentPane().add(boton_retirada6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        boton_retirada7.setText("Retirar");
        boton_retirada7.setFocusPainted(false);
        boton_retirada7.setFocusable(false);
        boton_retirada7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_retirada7ActionPerformed(evt);
            }
        });
        getContentPane().add(boton_retirada7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        boton_retirada8.setText("Retirar");
        boton_retirada8.setFocusPainted(false);
        boton_retirada8.setFocusable(false);
        boton_retirada8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_retirada8ActionPerformed(evt);
            }
        });
        getContentPane().add(boton_retirada8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        boton_retirada9.setText("Retirar");
        boton_retirada9.setFocusPainted(false);
        boton_retirada9.setFocusable(false);
        boton_retirada9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_retirada9ActionPerformed(evt);
            }
        });
        getContentPane().add(boton_retirada9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, -1, -1));

        boton_retirada10.setText("Retirar");
        boton_retirada10.setFocusPainted(false);
        boton_retirada10.setFocusable(false);
        boton_retirada10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_retirada10ActionPerformed(evt);
            }
        });
        getContentPane().add(boton_retirada10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 610, -1, -1));

        jButton1.setText("Menú");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 410, -1, 31));

        jButton2.setText("X");
        jButton2.setBorderPainted(false);
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, -1, -1));

        boton_retirada.setText("Retirar");
        boton_retirada.setFocusPainted(false);
        boton_retirada.setFocusable(false);
        boton_retirada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_retiradaActionPerformed(evt);
            }
        });
        getContentPane().add(boton_retirada, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 600, -1, -1));

        carro_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/carro3_1.png"))); // NOI18N
        Cajones a100 = new Cajones();
        Cajones a101 = new Cajones(a100.ConsultaCajon(1));
        carro_1.setIcon(new javax.swing.ImageIcon(getClass().getResource(a101.TipoImagen(2))));
        carro_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                carro_1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                carro_1MouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carro_1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                carro_1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                carro_1MouseEntered(evt);
            }
        });
        getContentPane().add(carro_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 80, 90, 110));

        carro_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/carro3_1.png"))); // NOI18N
        Cajones a2 = new Cajones();
        Cajones a22 = new Cajones(a2.ConsultaCajon(2));
        carro_2.setIcon(new javax.swing.ImageIcon(getClass().getResource(a22.TipoImagen(2))));
        carro_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                carro_2MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                carro_2MouseEntered(evt);
            }
        });
        getContentPane().add(carro_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, 100, 110));

        carro_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/carro3_1.png"))); // NOI18N
        Cajones a3 = new Cajones();
        Cajones a33 = new Cajones(a3.ConsultaCajon(3));
        carro_3.setIcon(new javax.swing.ImageIcon(getClass().getResource(a33.TipoImagen(2))));
        carro_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                carro_3MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                carro_3MouseEntered(evt);
            }
        });
        getContentPane().add(carro_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, 90, 120));

        carro_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/carro2_1.png"))); // NOI18N
        Cajones a4 = new Cajones();
        Cajones a44 = new Cajones(a4.ConsultaCajon(4));
        carro_4.setIcon(new javax.swing.ImageIcon(getClass().getResource(a44.TipoImagen(3))));
        carro_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                carro_4MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                carro_4MouseEntered(evt);
            }
        });
        getContentPane().add(carro_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 150, 50));

        carro_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/carro2_1.png"))); // NOI18N
        Cajones a6 = new Cajones();
        Cajones a66 = new Cajones(a6.ConsultaCajon(6));
        carro_6.setIcon(new javax.swing.ImageIcon(getClass().getResource(a66.TipoImagen(3))));
        carro_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                carro_6MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                carro_6MouseEntered(evt);
            }
        });
        getContentPane().add(carro_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 150, 50));

        carro_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/carro2_1.png"))); // NOI18N
        Cajones a5 = new Cajones();
        Cajones a55 = new Cajones(a5.ConsultaCajon(5));
        carro_5.setIcon(new javax.swing.ImageIcon(getClass().getResource(a55.TipoImagen(3))));
        carro_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                carro_5MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                carro_5MouseEntered(evt);
            }
        });
        getContentPane().add(carro_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 150, 100));

        carro_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/image3004.png"))); // NOI18N
        Cajones a7 = new Cajones();
        Cajones a77 = new Cajones(a7.ConsultaCajon(7));
        carro_7.setIcon(new javax.swing.ImageIcon(getClass().getResource(a77.TipoImagen(1))));
        carro_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                carro_7MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                carro_7MouseEntered(evt);
            }
        });
        getContentPane().add(carro_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 150, 50));

        carro_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/image3004.png"))); // NOI18N
        Cajones a8 = new Cajones();
        Cajones a88 = new Cajones(a8.ConsultaCajon(8));
        carro_8.setIcon(new javax.swing.ImageIcon(getClass().getResource(a88.TipoImagen(1))));
        carro_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                carro_8MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                carro_8MouseEntered(evt);
            }
        });
        getContentPane().add(carro_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 150, 50));

        carro_9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/image3004.png"))); // NOI18N
        Cajones a9 = new Cajones();
        Cajones a99 = new Cajones(a9.ConsultaCajon(9));
        carro_9.setIcon(new javax.swing.ImageIcon(getClass().getResource(a99.TipoImagen(1))));
        carro_9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                carro_9MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                carro_9MouseEntered(evt);
            }
        });
        getContentPane().add(carro_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 140, 50));

        carro_10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/carro2.png"))); // NOI18N
        Cajones a102 = new Cajones();
        Cajones a10 = new Cajones(a102.ConsultaCajon(10));
        carro_10.setIcon(new javax.swing.ImageIcon(getClass().getResource(a10.TipoImagen(1))));
        carro_10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                carro_10MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                carro_10MouseEntered(evt);
            }
        });
        getContentPane().add(carro_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 640, 150, 60));

        carro_11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/carro3_1.png"))); // NOI18N
        Cajones a113 = new Cajones();
        Cajones a11 = new Cajones(a113.ConsultaCajon(11));
        carro_11.setIcon(new javax.swing.ImageIcon(getClass().getResource(a11.TipoImagen(2))));
        carro_11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                carro_11MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                carro_11MouseEntered(evt);
            }
        });
        getContentPane().add(carro_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 640, 90, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/Parqueo.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1110, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void accion(int num){
        ret.retiro_mapa(num);
        ret.setVisible(true);
        this.dispose();
        }
    
    
    private void actualizar_carros(){ //cuando se inicia el mapa pintamos los cajones.
        while (L<12){
            Cajones cajon= new Cajones(L);
         //   System.out.println(cajon.getEstado());
          if(cajon.getEstado()==0){
         if(L==1){
             this.carro_1.setVisible(false);
             
         }
         
          if(L==2){
             this.carro_2.setVisible(false);
             
         }
          
           if(L==3){
             this.carro_3.setVisible(false);
             
         }
           
            if(L==4){
             this.carro_4.setVisible(false);
             
         }
            
             if(L==5){
             this.carro_5.setVisible(false);
             
         }
             
              if(L==6){
             this.carro_6.setVisible(false);
             
         }
              
               if(L==7){
             this.carro_7.setVisible(false);
             
         }
               
                if(L==8){
             this.carro_8.setVisible(false);
             
         }
                
                 if(L==9){
             this.carro_9.setVisible(false);
             
         }
                 
                  if(L==10){
             this.carro_10.setVisible(false);
             
         }
                  
                   if(L==11){
             this.carro_11.setVisible(false);
             
         }
            
          L++;
          
        }
          else{   //Cambio
             if(L==1){
             this.carro_1.setVisible(true);
             
         }
         
          if(L==2){
             this.carro_2.setVisible(true);
             
         }
          
           if(L==3){
             this.carro_3.setVisible(true);
             
         }
           
            if(L==4){
             this.carro_4.setVisible(true);
             
         }
            
             if(L==5){
             this.carro_5.setVisible(true);
             
         }
             
              if(L==6){
             this.carro_6.setVisible(true);
             
         }
              
               if(L==7){
             this.carro_7.setVisible(true);
             
         }
               
                if(L==8){
             this.carro_8.setVisible(true);
             
         }
                
                 if(L==9){
             this.carro_9.setVisible(true);
             
         }
                 
                  if(L==10){
             this.carro_10.setVisible(true);
             
         }
                  
                   if(L==11){
             this.carro_11.setVisible(true);
             
         }
                   L++;   
             
          }         
        } 
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new menu().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           System.exit(0);   // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
//*********************************************INFO *****************************************
    //el secreto está en que cuando hacen focus al área del cajón mandamos a llamar la ventana que nos muestra
    // datos y además hacemos visible el boton para retirar.
    private void carro_1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carro_1MouseEntered
 info.actualizar_valor(1);
            info.actualizar_datos(1);
        info.setVisible(true); 
        info.setLayout(null);
        info.setBounds(620, 100, 220,240);
         //info.setBounds(510, 100, 220,240);
          //info.setBounds(410, 100, 220,240);
        this.boton_retirada1.setVisible(true);
    }//GEN-LAST:event_carro_1MouseEntered

    private void carro_1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carro_1MouseExited
        info.setVisible(false); 
       
        // TODO add your handling code here:
    }//GEN-LAST:event_carro_1MouseExited

    private void carro_2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carro_2MouseEntered
              this.boton_retirada2.setVisible(true);        
        System.out.println("esta en el"+2);
                        info.update();
         info.actualizar_valor(2);
        info.actualizar_datos(2);
        info.setVisible(true); 
        info.setLayout(null);
        info.setBounds(510, 100, 220,240);
              this.boton_retirada2.setVisible(true);

    }//GEN-LAST:event_carro_2MouseEntered

    private void carro_2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carro_2MouseExited
       info.setVisible(false); 
     
    }//GEN-LAST:event_carro_2MouseExited

    private void carro_3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carro_3MouseEntered
         info.actualizar_valor(3);
        info.actualizar_datos(3);
        info.setVisible(true); 
        info.setLayout(null);
        info.setBounds(410, 100, 220,240);
       this.boton_retirada3.setVisible(true);
    }//GEN-LAST:event_carro_3MouseEntered

    private void carro_3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carro_3MouseExited
         info.setVisible(false);
   
    }//GEN-LAST:event_carro_3MouseExited

    private void carro_4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carro_4MouseEntered
        info.update();
         info.actualizar_valor(4);
        info.actualizar_datos(4);
        info.setVisible(true); 
        info.setLayout(null);
        info.setBounds(150, 380, 220,240);
        this.boton_retirada6.setVisible(true);
    }//GEN-LAST:event_carro_4MouseEntered

    private void carro_4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carro_4MouseExited
    info.setVisible(false); 
   
    }//GEN-LAST:event_carro_4MouseExited

    private void carro_5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carro_5MouseEntered
        info.update();
         info.actualizar_valor(5);
        info.actualizar_datos(5);
        info.setVisible(true); 
        info.setLayout(null);
        info.setBounds(150, 200, 220,240);
       this.boton_retirada5.setVisible(true);
    }//GEN-LAST:event_carro_5MouseEntered

    private void carro_5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carro_5MouseExited
       info.setVisible(false); 
 
    }//GEN-LAST:event_carro_5MouseExited

    private void carro_6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carro_6MouseEntered
        info.update();
         info.actualizar_valor(6);
        info.actualizar_datos(6);
        info.setVisible(true); 
        info.setLayout(null);
        info.setBounds(150, 100, 220,240);
       this.boton_retirada4.setVisible(true);
    }//GEN-LAST:event_carro_6MouseEntered

    private void carro_6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carro_6MouseExited
       info.setVisible(false); 
 
    }//GEN-LAST:event_carro_6MouseExited

    private void carro_7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carro_7MouseEntered
        info.update();
         info.actualizar_valor(7);
        info.actualizar_datos(7);
        info.setVisible(true); 
        info.setLayout(null);
        info.setBounds(350, 380, 220,240);
       this.boton_retirada7.setVisible(true);
    }//GEN-LAST:event_carro_7MouseEntered

    private void carro_7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carro_7MouseExited
       info.setVisible(false);

    }//GEN-LAST:event_carro_7MouseExited

    private void carro_8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carro_8MouseEntered
                info.update();
         info.actualizar_valor(8);
                info.actualizar_datos(8);
        info.setVisible(true); 
        info.setLayout(null);
        info.setBounds(350, 200, 220,240);
       this.boton_retirada8.setVisible(true);
    }//GEN-LAST:event_carro_8MouseEntered

    private void carro_8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carro_8MouseExited
        info.setVisible(false);

    }//GEN-LAST:event_carro_8MouseExited

    private void carro_9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carro_9MouseEntered
        info.update();
         info.actualizar_valor(9);
        info.actualizar_datos(9);
        info.setVisible(true); 
        info.setLayout(null);
        info.setBounds(350, 100, 220,240);
        this.boton_retirada9.setVisible(true);
    }//GEN-LAST:event_carro_9MouseEntered

    private void carro_9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carro_9MouseExited
        info.setVisible(false);
       
    }//GEN-LAST:event_carro_9MouseExited

    private void carro_10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carro_10MouseEntered
               // info.update();
             info.actualizar_valor(10);
               info.actualizar_datos(10);
        info.setVisible(true); 
        info.setLayout(null);
             //info.setBounds(350, 100, 220,240);
             info.setBounds(630, 120, 220,240);
         this.boton_retirada1.setVisible(true);
    }//GEN-LAST:event_carro_10MouseEntered

    private void carro_10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carro_10MouseExited
        info.setVisible(false);
     
    }//GEN-LAST:event_carro_10MouseExited

    private void carro_11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carro_11MouseEntered
                info.update();
         info.actualizar_valor(11);
                info.actualizar_datos(11);
        info.setVisible(true); 
        info.setLayout(null);
        info.setBounds(630, 410, 220,240);
      this.boton_retirada.setVisible(true);
         
    }//GEN-LAST:event_carro_11MouseEntered

    private void carro_11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carro_11MouseExited
        info.setVisible(false);
    
    }//GEN-LAST:event_carro_11MouseExited

    private void boton_retiradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_retiradaActionPerformed
            ret.setVisible(true);
             ret.retiro_mapa(11);
             this.dispose();
             info.dispose();
             
    }//GEN-LAST:event_boton_retiradaActionPerformed

    private void boton_retirada1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_retirada1ActionPerformed
             ret.setVisible(true);
             ret.retiro_mapa(1);
             this.dispose();
             info.dispose();        // TODO add your handling code here:
                      ret.dispose();
    }//GEN-LAST:event_boton_retirada1ActionPerformed

    private void boton_retirada2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_retirada2ActionPerformed
       ret.setVisible(true);
             ret.retiro_mapa(2);
             this.dispose();
             info.dispose();
             ret.dispose();
    }//GEN-LAST:event_boton_retirada2ActionPerformed

    private void boton_retirada3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_retirada3ActionPerformed
       ret.setVisible(true);
             ret.retiro_mapa(3);
             this.dispose();
             info.dispose();
    }//GEN-LAST:event_boton_retirada3ActionPerformed

    private void boton_retirada4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_retirada4ActionPerformed
       ret.setVisible(true);
             ret.retiro_mapa(6);
             this.dispose();
             info.dispose();
    }//GEN-LAST:event_boton_retirada4ActionPerformed

    private void boton_retirada5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_retirada5ActionPerformed
       ret.setVisible(true);
             ret.retiro_mapa(5);
             this.dispose();
             info.dispose();
    }//GEN-LAST:event_boton_retirada5ActionPerformed

    private void boton_retirada6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_retirada6ActionPerformed
        ret.setVisible(true);
             ret.retiro_mapa(4);
             this.dispose();
             info.dispose();
    }//GEN-LAST:event_boton_retirada6ActionPerformed

    private void boton_retirada7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_retirada7ActionPerformed
       ret.setVisible(true);
             ret.retiro_mapa(7);
             this.dispose();
             info.dispose();
    }//GEN-LAST:event_boton_retirada7ActionPerformed

    private void boton_retirada8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_retirada8ActionPerformed
        ret.setVisible(true);
             ret.retiro_mapa(8);
             this.dispose();
             info.dispose();
    }//GEN-LAST:event_boton_retirada8ActionPerformed

    private void boton_retirada9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_retirada9ActionPerformed
        ret.setVisible(true);
             ret.retiro_mapa(9);
             this.dispose();
             info.dispose();
    }//GEN-LAST:event_boton_retirada9ActionPerformed

    private void boton_retirada10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_retirada10ActionPerformed
        ret.setVisible(true);
             ret.retiro_mapa(10);
             this.dispose();
             info.dispose();
    }//GEN-LAST:event_boton_retirada10ActionPerformed

    private void carro_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carro_1MouseClicked
        System.out.println("esta en el"+1);
info.actualizar_datos(1);
        info.setVisible(true); 
        info.setLayout(null);
        info.setBounds(259, 400, 220,240);
         this.boton_retirada1.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_carro_1MouseClicked

    private void carro_1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carro_1MousePressed
        System.out.println("esta en el"+1);
info.actualizar_datos(1);
        info.setVisible(true); 
        info.setLayout(null);
        info.setBounds(259, 400, 220,240);
         this.boton_retirada1.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_carro_1MousePressed

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        //initComponents();
    }//GEN-LAST:event_jLabel1MouseEntered

    private void carro_1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carro_1MouseReleased
        // TODO add your handling code here:
                System.out.println("esta en el"+1);
info.actualizar_datos(1);
        info.setVisible(true); 
        info.setLayout(null);
        info.setBounds(259, 400, 220,240);
         this.boton_retirada1.setVisible(true);
    }//GEN-LAST:event_carro_1MouseReleased

      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                mapa map=new mapa();
                        map.setVisible(true);
                       
                        
                       
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_retirada;
    private javax.swing.JButton boton_retirada1;
    private javax.swing.JButton boton_retirada10;
    private javax.swing.JButton boton_retirada2;
    private javax.swing.JButton boton_retirada3;
    private javax.swing.JButton boton_retirada4;
    private javax.swing.JButton boton_retirada5;
    private javax.swing.JButton boton_retirada6;
    private javax.swing.JButton boton_retirada7;
    private javax.swing.JButton boton_retirada8;
    private javax.swing.JButton boton_retirada9;
    public javax.swing.JLabel carro_1;
    public javax.swing.JLabel carro_10;
    public javax.swing.JLabel carro_11;
    public javax.swing.JLabel carro_2;
    public javax.swing.JLabel carro_3;
    public javax.swing.JLabel carro_4;
    public javax.swing.JLabel carro_5;
    public javax.swing.JLabel carro_6;
    public javax.swing.JLabel carro_7;
    public javax.swing.JLabel carro_8;
    public javax.swing.JLabel carro_9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
