/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Clases.DB;
import Clases.Recibos;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Iterator;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element; 
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.io.File;
/**
 *
 * @author JODA
 */
public class Reportes extends javax.swing.JFrame {
   DB base= new DB();  //instanciamos la clase de conexión
Connection conexion= base.GetConnection(); //obtenermos conexión con ayuda de la clase
File ruta= new File("");
String rutarel = ruta.getAbsolutePath(); //obtenemos la ruta raíz
    /**
     * Creates new form Reportes
     */
    public Reportes() { //quitamos adornos y establecemos locación
        this.setUndecorated(true);
        this.setLocation(400, 100);
        initComponents();
        carga.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        carga = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Regresar al menú");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, 140, 38));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/flat/icopedf.png"))); // NOI18N
        jButton2.setText("Hacer reporte!");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 500, 140, 38));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/flat/edit-button-128.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, -1));

        carga.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        carga.setForeground(new java.awt.Color(255, 0, 0));
        carga.setText("esto puede tardar varios segundos");
        getContentPane().add(carga, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 240, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/pdf.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 450, 390));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/flat/close.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 30, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/flat/template_ventana_menu.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, 690, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     */
    public void obtener_recibos()throws IOException, DocumentException{
       Recibos recibo= new Recibos();  //creamos el pdf desde cero
Document document = new Document(PageSize.LETTER , 36, 36, 54, 36); //creamos una nueva hoja.
Image imagen = Image.getInstance("logo_chico.png"); //instanciamos recursos gráficos
File ruta= new File("");
String rutarel = ruta.getAbsolutePath();
PdfWriter.getInstance(document, new FileOutputStream(rutarel+"\\Reporte_Estacionamiento.pdf"));//creamos título para el documento
 imagen.setAlignment(Element.ALIGN_LEFT);
 document.open(); //empezamos a añadir cosas al pdf
 document.add(new Paragraph("Reporte de los recibo"));
 document.add(imagen);
 document.add(new Paragraph("\t\tServicio de estacionamiento y seguridad vehicular.\n RFC: EST235613 Rep. Legal Jorge Alberto Márquez\n"
                + "Colima Col.             Tel: 312 23423534"));
 document.add(new Paragraph("Registro de los reportes: \n\n\n\n"));   
 for(int i=0;i<recibo.getClientes().size();i++){
         PdfPTable tabla = new PdfPTable(1);
         String client=recibo.getClientes().get(i).getCliente();
         String folio=String.valueOf(recibo.getClientes().get(i).getFolio());
         String fecha= recibo.getClientes().get(i).getFecha();
         String pago=String.valueOf(recibo.getClientes().get(i).getImporte());
        System.out.println(client);
         tabla.addCell("Reporte");   //se crea reporte por cada recibo
         tabla.addCell("Folio: "+folio+"   Cliente: "+client+"    Fecha: "+fecha+"   Pago:"+pago);
         
         document.add(tabla);
     }
    JOptionPane.showMessageDialog(null,"PDF Generado !", "Carga hecha",1);
     document.close();  
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new menu().setVisible(true);
            this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
     
        try {
            obtener_recibos();    // TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
             File file = new File(rutarel+"\\Reporte_Estacionamiento.pdf"); //abrimos el documento luego de ser creado.
             Desktop.getDesktop().open(file);
            } catch(Exception e) {
               e.printStackTrace();
                }
        this.carga.setVisible(false);
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel carga;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
